#!/bin/bash

for i in {1..100}
do
 rtt=$(ping -c 1 -W 5 192.168.1.1 | grep -i "time=" | tr '\n' ' ')
 if [ "$rtt" ]
 then
  rssi=$(iwconfig wlp2s0 | grep -i "signal")
  echo $rtt $rssi >> $1
  echo $i $rtt $rssi
 else
  echo $i
 fi
 
 sleep 1
done

